FROM node:16-alpine AS development

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml .npmrc ./

RUN pnpm install --frozen-lockfile

COPY . .

CMD ["pnpm", "run", "start:dev"]
