version: '3'
services:
  nest-api-postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=nest_api_user
      - POSTGRES_PASSWORD=nest_api_pwd
      - POSTGRES_DB=nest_api_starter_db

  redis:
    image: redis
    ports:
      - '6379:6379'
