server:
  port: 7777
  origin: 'http://localhost:3000'

db:
  host: ''
  type: ''
  port: 5432
  database: 'nest_api_starter'
  synchronize: false

jwt:
  expiresIn: 900
  refreshExpiresIn: 604800
  cookieExpiresIn: 604800

app:
  name: 'Nest API Starter'
  version: 'v1.0'
  description: 'NestJS API starter template'
  appUrl: 'http://localhost:7777'
  frontendUrl: 'http://localhost:3000'

mail:
  host: ''
  port: 2525
  user: ''
  pass: ''
  from: 'nest-api-starter'
  fromMail: 'noreply@example.com'
  preview: true
  secure: false
  ignoreTLS: true
  queueName: 'nest-api-mail'

queue:
  driver: 'redis'
  host: 'localhost'
  port: 6379
  db: ''
  password: ''
  username: ''

throttle:
  global:
    ttl: 60
    limit: 60
  login:
    prefix: 'login_fail_throttle'
    limit: 5
    duration: 2592000
    blockDuration: 3000
